### ISSUE TITLE
Couldn't load 12 pt font from FreeMono.ttf: Couldn't open FreeMono.ttf

### ISSUE THREAD

**Issue by bam80** [LBALab/twin-e#20]
I have to
`ln -s /usr/share/fonts/TTF/FreeMono.ttf .`
in LBA dir to make it work

**Comment by xesf** [comment]
That should only be used if GAMEMOD enabled, although having the font on the root directory should have worked.

**Comment by bam80** [comment]
What do you mean GAMEMOD? I just followed README compile instructions and it didn't work until FreeMono.ttf placed to the root.

**Comment by xesf** [comment]
I got rid of this recently and TTF is enabled by default for now. The font is available in the ./bin folder so the game run should work fine.

The idea is to get rid of the TTF dependency completely and go back to something close to the original, having some sort of DOS pixel 8x8 font.
